version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    groups:
      # group simple version updates, leave major updates and security updates as single pull requests
      minor-and-patch:
        update-types:
          - "patch"
          - "minor"
        applies-to:
          - "version-updates"
      eslint:
        patterns:
          - "@eslint-community/*"
          - "@eslint/*"
          - "@types/eslint*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "typescript-eslint*"
  - package-ecosystem: "github-actions"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
